### PR TITLE
modified authorized page - kept light and simple, incorporated font a…

### PR DESCRIPTION
**Pull request by hougasian**
…wesome
screen shot 2015-10-26 at 2 24 45 pm

### CODE REVIEW

**Comment by hougasian** [comment]
in response to #3

**Comment by jchannon** [comment]
Holy design skills batman! This is awesome. Thank you so much!!

**Comment by hougasian** [comment]
Not a problem!

**Comment by jchannon** [comment]
https://twitter.com/jchannon/status/658711772958953472

**Pull request merged**
